@startuml
title Sombra

rectangle Luz
rectangle Objeto
rectangle Sombra
rectangle Superficie

Luz -up-> Objeto : alcanza
Objeto -right-> Sombra : genera
Sombra -down-> Superficie : se refleja en
@enduml